const mongoose = require('mongoose');

const { Schema } = mongoose;

const answerSchema = new Schema({
  name: String,
  dob: Date,
  age: String,
  marital: String,
  email: String,
  phone: String,
  academic: String,
  professional: String,
  experience: Array,
  processing: String,
  impairment: String,
  impairments: String,
  identification: String,
  passport: String,
  ig: String,
  fb: String,
  tw: String,
  about: String,
  why: String,
  occupation: String,
  ex_poe: String,
  duration: String,
  poe: String,
  salary: String,
  nysc: String,
  state: String,
  batch: String,
  nysc_num: String,
  pop: String,
  weekends: String,
  availability: String,
  unavailability: String,
  class_time: String,
  transport: String,
  absent_days: String,
  laptop: String,
  laptop_tlw: String,
  laptop_owner: String,
  laptop_loan: String,
  ram: String,
  cpu: String,
  lp_condition: String,
  power: String,
  internet: String,
  ex_student: String,
  sm_act: String,
  no_sm_act: String,
  sm_follow: String,
  no_sm_follow: String,
  sm_like: String,
  no_sm_like: String,
  sm_comment: String,
  no_sm_comment: String,
  sm_tagging: String,
  no_sm_tagging: String,
  sm_share: String,
  no_sm_share: String,
  sm_testimonial: String,
  no_sm_testimonial: String,
  sm_screenshot: String,
  no_sm_screenshot: String,
  sm_media: String,
  no_sm_media: String,
  rules: String,
  bylaws: String,
  no_byelaws: String,
  dedication: String,
  date: {
    type: Date,
    default: Date.now()
  }
});

module.exports = mongoose.model('Answer', answerSchema);
